# from task 2 - k8s sa for the app, workload identity maps it to the cm-app gsa from task 1
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-ksa
  namespace: app
  annotations:
    iam.gke.io/gcp-service-account: cm-app@cloud-mile-assessment.iam.gserviceaccount.com
